# Generated by Django 2.0.5 on 2018-05-22 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issn', models.BigIntegerField()),
                ('print_year', models.IntegerField()),
                ('author', models.CharField(max_length=120)),
                ('translator', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('stock_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unilibrary.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unilibrary.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('student_number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unilibrary.Book')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unilibrary.Person')),
            ],
        ),
        migrations.AddField(
            model_name='donate',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unilibrary.Person'),
        ),
        migrations.AddField(
            model_name='borrow',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unilibrary.Person'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unilibrary.BookType'),
        ),
    ]
